# Generated by Django 5.0.4 on 2024-04-12 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_rename_test_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255)),
                ('mymodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.mymodel')),
            ],
        ),
    ]
