# Generated by Django 5.0.4 on 2024-04-12 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0004_order2_order3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mymodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='signals.mymodel'),
        ),
        migrations.AlterField(
            model_name='order2',
            name='mymodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='signals.mymodel'),
        ),
        migrations.AlterField(
            model_name='order3',
            name='mymodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='signals.mymodel'),
        ),
    ]
