# Generated by Django 5.0.4 on 2024-04-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0005_alter_order_mymodel_alter_order2_mymodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mymodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.mymodel'),
        ),
        migrations.AlterField(
            model_name='order2',
            name='mymodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.mymodel'),
        ),
        migrations.AlterField(
            model_name='order3',
            name='mymodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.mymodel'),
        ),
    ]
