# Generated by Django 5.0.4 on 2024-04-12 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0006_alter_order_mymodel_alter_order2_mymodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order3',
            name='mymodel',
        ),
        migrations.AlterField(
            model_name='order',
            name='mymodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signals.mymodel'),
        ),
        migrations.DeleteModel(
            name='Order2',
        ),
        migrations.DeleteModel(
            name='Order3',
        ),
    ]
