# Generated by Django 5.0.4 on 2024-04-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0007_remove_order3_mymodel_alter_order_mymodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
